# https://starship.rs/config/#prompt

# Don't print a new line at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """\
  $time\
  $directory\
  $git_branch\
  $git_state\
  $git_status\
  $cmd_duration\
  $battery\
  $character\
  """

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
format = "➜ "     # The "symbol" segment is being set to "➜"

[directory]
truncate_to_repo = true
truncation_length = 2
fish_style_pwd_dir_length = 2

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[time]
disabled = false
style = "blue"
time_format = "%I:%M%P"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


